# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Queens College Data Science & AI Club
tagline:          Data Science and AI Club
description:      "A collaborative learning place for people who are interested in learning about Data Science and Artificial Intelligence"
url:              https://datascience-ai-qc.github.io
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Muhammad
  url:            https://twitter.com/muhammad_o7

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc
